# Generated by Django 3.1.3 on 2020-11-25 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
